<a href="https://colab.research.google.com/github/rupadhya-byte/FDS-lab/blob/main/fdsiris_dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("Iris.csv")

In [3]:
df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             150 non-null    int64
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB

In [5]:
numeric = df.select_dtypes(include='number')
numeric

      Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0      1            5.1           3.5            1.4           0.2
1      2            4.9           3.0            1.4           0.2
2      3            4.7           3.2            1.3           0.2
3      4            4.6           3.1            1.5           0.2
4      5            5.0           3.6            1.4           0.2
..   ...            ...           ...            ...           ...
145  146            6.7           3.0            5.2           2.3
146  147            6.3           2.5            5.0           1.9
147  148            6.5           3.0            5.2           2.0
148  149            6.2           3.4            5.4           2.3
149  150            5.9           3.0            5.1           1.8

[150 rows x 5 columns]

In [6]:
mean = numeric.mean()
print("Mean")
print(mean)

Mean
Id               75.500000
SepalLengthCm     5.843333
SepalWidthCm      3.054000
PetalLengthCm     3.758667
PetalWidthCm      1.198667
dtype: float64

In [7]:
median = numeric.median()
print("Median")
print(median)

Median
Id               75.50
SepalLengthCm     5.80
SepalWidthCm      3.00
PetalLengthCm     4.35
PetalWidthCm      1.30
dtype: float64

In [8]:
mode = numeric.mode()

print("Mode")
print(mode)

Mode
      Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0      1            5.0           3.0            1.5           0.2
1      2            NaN           NaN            NaN           NaN
2      3            NaN           NaN            NaN           NaN
3      4            NaN           NaN            NaN           NaN
4      5            NaN           NaN            NaN           NaN
..   ...            ...           ...            ...           ...
145  146            NaN           NaN            NaN           NaN
146  147            NaN           NaN            NaN           NaN
147  148            NaN           NaN            NaN           NaN
148  149            NaN           NaN            NaN           NaN
149  150            NaN           NaN            NaN           NaN

[150 rows x 5 columns]

In [9]:
summary = pd.DataFrame({
    "Mean": numeric.mean(),
    "Median": numeric.median(),
    "Mode": numeric.mode().iloc[0]
})

print(summary)

                    Mean  Median  Mode
Id             75.500000   75.50   1.0
SepalLengthCm   5.843333    5.80   5.0
SepalWidthCm    3.054000    3.00   3.0
PetalLengthCm   3.758667    4.35   1.5
PetalWidthCm    1.198667    1.30   0.2